import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/style/globals.css";
import { Providers } from "./providers";
import clsx from "clsx";
import { fontSans } from "@/config/fonts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default async function RootLayout({ children }: Props) {
  return (
    <html suppressHydrationWarning>
      <body
        className={clsx(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Providers themeProps={{ attribute: "class", defaultTheme: "dark" }}>
          <div className="flex flex-col h-screen">
            <div className="p-1 md:p-4 h-full">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
